name: Version bump (test)
on:
# pull_request -> GITHUB_TOKEN has no write permissions on external forks
#  pull_request:
#    types:
#      - labeled
#
# pull_request_target -> GITHUB_TOKEN has write permissions external forks
  pull_request:
    types:
      - labeled
      - unlabeled

env:
  NODE_VERSION: 20

permissions:
  contents: write
  pull-requests: write

jobs:
  version-bump-test-1:
    if: github.event.label.name == 'pr-version-bump'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Test bump action
        with:
          user_name: 'drassil-git-bot'
          user_email: 'drassil-git-bot@drassil.org'
          ref_branch: 'main'
          version_args: 'patch'
          node_version: ${{ env.NODE_VERSION }}
        uses: ./

      - name: Test restore action
        with:
          user_name: 'drassil-git-bot'
          user_email: 'drassil-git-bot@drassil.org'
          ref_branch: 'main'
          version_args: 'patch'
          node_version: ${{ env.NODE_VERSION }}
          action: 'restore'
        uses: ./

  version-bump-test-2:
    if: github.event.label.name == 'pr-version-bump'
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Test bump action (without push)
        with:
          user_name: 'drassil-git-bot'
          user_email: 'drassil-git-bot@drassil.org'
          ref_branch: 'main'
          version_args: 'patch'
          node_version: ${{ env.NODE_VERSION }}
          skip_push: true
        uses: ./